[project]
name = "chat2rag"
version = "0.1.0"
description = "与大模型交互的RAG问答系统"
readme = "README.md"
maintainers = [{ name = "Jacob Zheng", email = "1453366421@qq.com" }]
requires-python = ">=3.9"
dependencies = [
    # 核心RAG组件
    "haystack-ai==2.8.0",
    "qdrant-haystack==7.0.0",
    "sentence-transformers>=2.3.0",

    # 监控和性能
    "openinference-instrumentation-haystack==0.1.12",
    "opentelemetry-sdk==1.29.0",
    "opentelemetry-exporter-otlp==1.29.0",
    "arize-phoenix==7.1.1",
    "pyinstrument==5.0.0",

    # Web服务
    "fastapi==0.115.6",
    "uvicorn[standard]==0.34.0",

    # 界面
    "streamlit==1.41.1",

    # 工具库
    "pyhumps==3.8.0",
    "python-dotenv>=1.0.0",
    "fuzzywuzzy==0.18.0",
    "python-Levenshtein>=0.26.1",
    "jsonref==1.1.0",
    "jsonschema>=4.23.0",

    # 农历
    "zhdate==0.1",
    "lunar-python==1.3.12"
]

[project.optional-dependencies]
dev = [
    "pytest==8.3.4",
    "fastapi-cache2[redis]==0.2.2",
    "black",          # 代码格式化
    "isort",          # import排序
    "mypy",           # 类型检查
    "pre-commit"      # git hooks
]

[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"


[tool.setuptools]
packages = ["rag_core","backend"]