name: chat2rag
services:
  service:
    image: jacob0827/chat2rag:latest
    container_name: service
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - ${DATA_PATH}/phoenix:/.phoenix
      - ${LOG_PATH}:/code/logs
    depends_on:
      postgresql:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    environment:
      - TZ=Asia/Shanghai
      - QDRANT_HOST=qdrant
      - POSTGRESQL_HOST=postgresql
    env_file:
      - ../.env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v1/health" ]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 30s
    networks:
      - chat2rag-network
    restart: always

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    healthcheck:
      test: [ "CMD", "/bin/bash", "-c", '</dev/tcp/localhost/6333' ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ${DATA_PATH}/qdrant_storage:/qdrant/storage
    env_file:
      - ../.env
    networks:
      - chat2rag-network
    restart: always

  postgresql:
    image: timescale/timescaledb:latest-pg17-bitnami
    container_name: postgresql
    ports:
      - "5432:5432"
    volumes:
      - ${DATA_PATH}/postgresql:/bitnami/postgresql
    environment:
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_SHARED_BUFFERS=1GB # 设置数据库共享内存缓冲区大小，建议设置为服务器内存的25%，更大的值可以提高读取性能
      - POSTGRESQL_MAX_CONNECTIONS=50 # 控制数据库最大并发连接数，需要根据服务器资源和应用需求设置
      - TZ=Asia/Shanghai # 设置容器时区为中国时区
      - POSTGRESQL_TIMEZONE=Asia/Shanghai # 设置PostgreSQL时区
      - POSTGRESQL_INITDB_ARGS=--data-checksums --encoding=UTF8 --locale=C --timezone=Asia/Shanghai # 初始化参数
    env_file:
      - ../.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres && PGPASSWORD=${POSTGRESQL_PASSWORD} psql -U postgres -d ${POSTGRESQL_DATABASE} -c 'SELECT 1'" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - chat2rag-network
    restart: always
    
  mysql:
    # image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mysql:8.0.36 # 阿里云
    image: mysql:8.0.36
    container_name: mysql
    restart: always
    ports:
      - 7586:3306
    networks:
      - chat2rag-network
    command: --default-authentication-plugin=mysql_native_password
    environment:
      # 默认root密码，仅首次运行有效
      MYSQL_ROOT_PASSWORD: Aa@123123
      MYSQL_DATABASE: oneapi
    volumes:
      - ${DATA_PATH}/mysql:/var/lib/mysql

networks:
  chat2rag-network:
    driver: bridge
