name: chat2rag
services:
  backend:
    image: jacob0827/chat2rag-backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ${DATA_PATH}/phoenix:/.phoenix
      - ${LOG_PATH}:/code/logs
    depends_on:
      - qdrant
    environment:
      - TZ=Asia/Shanghai
      - QDRANT_HOST=qdrant
    env_file:
      - ../.env
    networks:
      - my-network
    restart: always

  frontend:
    image: jacob0827/chat2rag-frontend:latest
    container_name: frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - TZ=Asia/Shanghai
      - BACKEND_HOST=backend
      - BACKEND_PORT=8000
    networks:
      - my-network
    restart: always

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    healthcheck:
      test: [ "CMD", "/bin/bash", "-c", '</dev/tcp/localhost/6333' ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ${DATA_PATH}/qdrant_storage:/qdrant/storage
    env_file:
      - ../.env
    networks:
      - my-network
    restart: always

  xinference:
    image: xprobe/xinference:v1.1.1-cpu
    container_name: embedding-service
    ports:
      - "9998:9997"
    volumes:
      - ${MODEL_PATH}:/opt/model
      - ../scripts:/scripts
    environment:
      - XINFERENCE_HOME=/opt/model
    env_file:
      - ../.env
    command: xinference-local -H 0.0.0.0 --log-level debug
    networks:
      - my-network
    restart: always

networks:
  my-network:
    driver: bridge
