name: chat2rag
services:
  backend:
    image: chat2rag-backend:latest
    container_name: backend
    ports:
      - "8000:8000"
      - "6006:6006"
    volumes:
      - ${DATA_PATH}/phoenix:/.phoenix
      - ${EMBEDDING_MODEL_PATH}:/BigModels/360Zhinao-search
    depends_on:
      - qdrant
    environment:
      - EMBEDDING_MODEL_PATH=/BigModels/360Zhinao-search
      - QRANT_HOST=qdrant
    env_file:
      - ../.env
    networks:
      - my-network
    restart: always

  frontend:
    image: chat2rag-frontend:latest
    container_name: frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8000
    networks:
      - my-network
    restart: always

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    healthcheck:
      test: [ "CMD", "/bin/bash", "-c", '</dev/tcp/localhost/6333' ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ${DATA_PATH}/qdrant_storage:/qdrant/storage
    env_file:
      - ../.env
    networks:
      - my-network
    restart: always

networks:
  my-network:
    driver: bridge
