import re

BEHAVIOR_TAG_TYPES = ("EMOJI", "ACTION", "IMAGE", "VIDEO")

BEHAVIOR_TAG_PATTERN = re.compile(r"\[(EMOJI|ACTION|IMAGE|VIDEO):.*?\]")

TTS_PUNCTUATION_MARKS = [",", ".", "，", "。", "!", "?", "！", "？", "；", "：", "、"]

TTS_BATCH_TIMEOUT = 0.05
TTS_MAX_BATCH_SIZE = 5

AUDIO_QUEUE_MAX_SIZE = 100
TEXT_QUEUE_MAX_SIZE = 200

METRICS_BATCH_SIZE = 5
METRICS_BATCH_TIMEOUT = 1.0
